//
// ScanPassage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ScanPassage: Codable {

    public var style: ScanStyle
    public var points: [[ScanFrame]]

    public init(style: ScanStyle, points: [[ScanFrame]]) {
        self.style = style
        self.points = points
    }

}

